name: stesh_app_api
description: "Books App."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-191.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3 # For making HTTP requests
  flutter_bloc: ^8.0.1 # For state management
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

